<?php

namespace AppBundle\Repository;

/**
 * CurrencyRateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CurrencyRateRepository extends \Doctrine\ORM\EntityRepository
{
    public function getRecordCount()
    {
        return $this->createQueryBuilder('cr')
            ->select('count(cr.id)')
            ->getQuery()
            ->getSingleScalarResult();
    }

    public function getDataForCurrentPage($offset, $limit)
    {
        return $this->createQueryBuilder('cr')
            ->orderBy('cr.createdAt', 'DESC')
            ->setFirstResult(($offset - 1) * $limit)
            ->setMaxResults($limit)
            ->getQuery()
            ->getResult();

    }
}
